import numpy as np
# Calculate the total revenue generated by two product ctegories in a store.

# category1_revenue=np.array([500,600,700,800])
# category2_revenue=np.array([450,700,800,600])
# total_revenue=category1_revenue+category2_revenue
# print(total_revenue)

# Calculate the profit made by a company

# category1_revenue=np.array([10000,12000,11000,10500])
# category2_revenue=np.array([4000,5000,4500,4800])
# total_revenue=category1_revenue-category2_revenue
# print(total_revenue)

# Determine which products in a store are out of stock (Quantity is 0)
# inventory = np.array([10,0,5,0,20,0])
# print("index of out of stock items are:")
# for i in range(len(inventory)):
#     if inventory[i]==0:
#         print(i,end=" ")
# a=np.where(inventory==0)
# print(a)

# Calculate the total cost of items in a shopping cart considering the quality and price per item
# quantity=np.array([2,3,4,1])
# price_per_item=np.array([10,5,8,12],dtype=float)
# cost=quantity*price_per_item
# print(cost)
